// <auto-generated />
using System;
using Assel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Assel.Data.Migrations
{
    [DbContext(typeof(AsselDbContext))]
    partial class AsselDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assel")
                .HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("Assel.Entities.Fact", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FactText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PetType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Facts", "assel");
                });

            modelBuilder.Entity("Assel.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users", "assel");
                });

            modelBuilder.Entity("Assel.Entities.Fact", b =>
                {
                    b.HasOne("Assel.Entities.User", null)
                        .WithMany("Facts")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Assel.Entities.User", b =>
                {
                    b.Navigation("Facts");
                });
#pragma warning restore 612, 618
        }
    }
}
